import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSansFont = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMonoFont = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BaseLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSansFont.variable} ${geistMonoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}